#############################################################################
# Makefile for building: app_camera_basler
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  app_camera_basler.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile app_camera_basler.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = app_camera_basler1.0.0
DISTDIR = /home/rainbow/app_camera_basler/.tmp/app_camera_basler1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/pylon/lib/ -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/lib/x86_64-linux-gnu/ -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -L/opt/pylon/lib/ -lpylonbase -lpylonutility -lpylonc -lGCBase_gcc_v3_1_Basler_pylon_v3 -lGenApi_gcc_v3_1_Basler_pylon_v3 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		basler_camera.cpp moc_mainwindow.cpp \
		moc_basler_camera.cpp
OBJECTS       = main.o \
		mainwindow.o \
		basler_camera.o \
		moc_mainwindow.o \
		moc_basler_camera.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		app_camera_basler.pro mainwindow.h \
		basler_camera.h main.cpp \
		mainwindow.cpp \
		basler_camera.cpp
QMAKE_TARGET  = app_camera_basler
DESTDIR       = 
TARGET        = app_camera_basler


first: all
####### Build rules

app_camera_basler:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: app_camera_basler.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		app_camera_basler.pro
	$(QMAKE) -o Makefile app_camera_basler.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
app_camera_basler.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile app_camera_basler.pro

qmake_all: FORCE


all: Makefile app_camera_basler

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h basler_camera.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp basler_camera.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_basler_camera.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_basler_camera.cpp
moc_mainwindow.cpp: mainwindow.h \
		basler_camera.h \
		/opt/pylon/include/pylon/PylonIncludes.h \
		/opt/pylon/include/pylon/Platform.h \
		/opt/pylon/include/pylon/api_autoconf.h \
		/opt/pylon/include/pylon/PylonLinkage.h \
		/opt/pylon/include/GenICamVersion.h \
		/opt/pylon/include/_GenICamVersion.h \
		/opt/pylon/include/Base/GCLinkage.h \
		/opt/pylon/include/Base/GCTypes.h \
		/opt/pylon/include/Base/GCNamespace.h \
		/opt/pylon/include/Base/GCString.h \
		/opt/pylon/include/Base/GCStringVector.h \
		/opt/pylon/include/GenApi/GenApi.h \
		/opt/pylon/include/Base/GCBase.h \
		/opt/pylon/include/Base/GCArray.h \
		/opt/pylon/include/Base/GCException.h \
		/opt/pylon/include/Base/GCUtilities.h \
		/opt/pylon/include/Base/GCRTSSUtilities.h \
		/opt/pylon/include/GenApi/GenApiDll.h \
		/opt/pylon/include/GenApi/GenApiNamespace.h \
		/opt/pylon/include/GenApi/Pointer.h \
		/opt/pylon/include/GenICamFwd.h \
		/opt/pylon/include/GenApi/IEnumeration.h \
		/opt/pylon/include/GenApi/IEnumEntry.h \
		/opt/pylon/include/GenApi/IValue.h \
		/opt/pylon/include/GenApi/Types.h \
		/opt/pylon/include/GenApi/Autovector.h \
		/opt/pylon/include/GenApi/IBase.h \
		/opt/pylon/include/GenApi/Reference.h \
		/opt/pylon/include/GenApi/INode.h \
		/opt/pylon/include/GenApi/Container.h \
		/opt/pylon/include/GenApi/IFloat.h \
		/opt/pylon/include/GenApi/IInteger.h \
		/opt/pylon/include/GenApi/ICategory.h \
		/opt/pylon/include/GenApi/IRegister.h \
		/opt/pylon/include/GenApi/IBoolean.h \
		/opt/pylon/include/GenApi/IPort.h \
		/opt/pylon/include/GenApi/IPortRecorder.h \
		/opt/pylon/include/GenApi/IPortConstruct.h \
		/opt/pylon/include/GenApi/IChunkPort.h \
		/opt/pylon/include/GenApi/IString.h \
		/opt/pylon/include/GenApi/INodeMap.h \
		/opt/pylon/include/GenApi/Synch.h \
		/opt/pylon/include/GenApi/IDestroy.h \
		/opt/pylon/include/GenApi/IDeviceInfo.h \
		/opt/pylon/include/GenApi/ISelector.h \
		/opt/pylon/include/GenApi/ICommand.h \
		/opt/pylon/include/GenApi/IUserData.h \
		/opt/pylon/include/GenApi/NodeMapRef.h \
		/opt/pylon/include/GenApi/NodeMapFactory.h \
		/opt/pylon/include/GenApi/GenApiVersion.h \
		/opt/pylon/include/GenApi/NodeCallback.h \
		/opt/pylon/include/GenApi/Persistence.h \
		/opt/pylon/include/GenApi/StructPort.h \
		/opt/pylon/include/GenApi/PortImpl.h \
		/opt/pylon/include/GenApi/SelectorSet.h \
		/opt/pylon/include/GenApi/ISelectorDigit.h \
		/opt/pylon/include/GenApi/GenApiLinkage.h \
		/opt/pylon/include/pylon/stdinclude.h \
		/opt/pylon/include/pylon/TypeMappings.h \
		/opt/pylon/include/pylon/PylonBase.h \
		/opt/pylon/include/pylon/PylonVersionInfo.h \
		/opt/pylon/include/pylon/Info.h \
		/opt/pylon/include/pylon/TlInfo.h \
		/opt/pylon/include/pylon/DeviceClass.h \
		/opt/pylon/include/pylon/DeviceInfo.h \
		/opt/pylon/include/pylon/Container.h \
		/opt/pylon/include/pylon/InterfaceInfo.h \
		/opt/pylon/include/pylon/StaticDefectPixel.h \
		/opt/pylon/include/pylon/DeviceFactory.h \
		/opt/pylon/include/pylon/DeviceAccessMode.h \
		/opt/pylon/include/pylon/PylonVersionNumber.h \
		/opt/pylon/include/pylon/TransportLayer.h \
		/opt/pylon/include/pylon/Interface.h \
		/opt/pylon/include/pylon/TlFactory.h \
		/opt/pylon/include/pylon/EventAdapter.h \
		/opt/pylon/include/pylon/Callback.h \
		/opt/pylon/include/pylon/Device.h \
		/opt/pylon/include/pylon/WaitObject.h \
		/opt/pylon/include/pylon/WaitObjects.h \
		/opt/pylon/include/pylon/StreamGrabber.h \
		/opt/pylon/include/pylon/PixelType.h \
		/opt/pylon/include/pylon/Pixel.h \
		/opt/pylon/include/pylon/PixelTypeMapper.h \
		/opt/pylon/include/GenApi/IEnumerationT.h \
		/opt/pylon/include/GenApi/Compatibility.h \
		/opt/pylon/include/pylon/Result.h \
		/opt/pylon/include/pylon/PayloadType.h \
		/opt/pylon/include/pylon/ResultImage.h \
		/opt/pylon/include/pylon/Image.h \
		/opt/pylon/include/pylon/SharedByteBuffer.h \
		/opt/pylon/include/pylon/PylonDataComponent.h \
		/opt/pylon/include/pylon/PylonDataContainer.h \
		/opt/pylon/include/pylon/ChunkParser.h \
		/opt/pylon/include/pylon/EventGrabber.h \
		/opt/pylon/include/pylon/EventGrabberProxy.h \
		/opt/pylon/include/pylon/NodeMapProxy.h \
		/opt/pylon/include/pylon/AcquireSingleFrameConfiguration.h \
		/opt/pylon/include/pylon/InstantCamera.h \
		/opt/pylon/include/pylon/ImageEventHandler.h \
		/opt/pylon/include/pylon/GrabResultPtr.h \
		/opt/pylon/include/pylon/GrabResultData.h \
		/opt/pylon/include/pylon/ConfigurationEventHandler.h \
		/opt/pylon/include/pylon/CameraEventHandler.h \
		/opt/pylon/include/pylon/BufferFactory.h \
		/opt/pylon/include/pylon/SfncVersion.h \
		/opt/pylon/include/pylon/ECleanup.h \
		/opt/pylon/include/pylon/ERegistrationMode.h \
		/opt/pylon/include/pylon/ETimeoutHandling.h \
		/opt/pylon/include/pylon/_InstantCameraParams.h \
		/opt/pylon/include/pylon/ParameterIncludes.h \
		/opt/pylon/include/pylon/ArrayParameter.h \
		/opt/pylon/include/pylon/Parameter.h \
		/opt/pylon/include/pylon/BooleanParameter.h \
		/opt/pylon/include/pylon/CommandParameter.h \
		/opt/pylon/include/pylon/EnumParameter.h \
		/opt/pylon/include/pylon/FloatParameter.h \
		/opt/pylon/include/pylon/IntegerParameter.h \
		/opt/pylon/include/pylon/StringParameter.h \
		/opt/pylon/include/pylon/EnumParameterT.h \
		/opt/pylon/include/pylon/ConfigurationHelper.h \
		/opt/pylon/include/pylon/InstantCameraArray.h \
		/opt/pylon/include/pylon/AcquireContinuousConfiguration.h \
		/opt/pylon/include/pylon/SoftwareTriggerConfiguration.h \
		/opt/pylon/include/pylon/InstantInterface.h \
		/opt/pylon/include/pylon/_BaslerUniversalInterfaceParams.h \
		/opt/pylon/include/pylon/PylonUtilityIncludes.h \
		/opt/pylon/include/pylon/PylonUtility.h \
		/opt/pylon/include/pylon/PylonImage.h \
		/opt/pylon/include/pylon/PylonImageBase.h \
		/opt/pylon/include/pylon/ReusableImage.h \
		/opt/pylon/include/pylon/ImagePersistence.h \
		/opt/pylon/include/pylon/PixelData.h \
		/opt/pylon/include/pylon/PylonImageUserBufferEventHandler.h \
		/opt/pylon/include/pylon/ImageDecompressor.h \
		/opt/pylon/include/pylon/ImageFormatConverter.h \
		/opt/pylon/include/pylon/_ImageFormatConverterParams.h \
		/opt/pylon/include/pylon/FeaturePersistence.h \
		/opt/pylon/include/pylon/VideoWriter.h \
		/opt/pylon/include/pylon/_VideoWriterParams.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/app_camera_basler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/app_camera_basler -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_basler_camera.cpp: basler_camera.h \
		/opt/pylon/include/pylon/PylonIncludes.h \
		/opt/pylon/include/pylon/Platform.h \
		/opt/pylon/include/pylon/api_autoconf.h \
		/opt/pylon/include/pylon/PylonLinkage.h \
		/opt/pylon/include/GenICamVersion.h \
		/opt/pylon/include/_GenICamVersion.h \
		/opt/pylon/include/Base/GCLinkage.h \
		/opt/pylon/include/Base/GCTypes.h \
		/opt/pylon/include/Base/GCNamespace.h \
		/opt/pylon/include/Base/GCString.h \
		/opt/pylon/include/Base/GCStringVector.h \
		/opt/pylon/include/GenApi/GenApi.h \
		/opt/pylon/include/Base/GCBase.h \
		/opt/pylon/include/Base/GCArray.h \
		/opt/pylon/include/Base/GCException.h \
		/opt/pylon/include/Base/GCUtilities.h \
		/opt/pylon/include/Base/GCRTSSUtilities.h \
		/opt/pylon/include/GenApi/GenApiDll.h \
		/opt/pylon/include/GenApi/GenApiNamespace.h \
		/opt/pylon/include/GenApi/Pointer.h \
		/opt/pylon/include/GenICamFwd.h \
		/opt/pylon/include/GenApi/IEnumeration.h \
		/opt/pylon/include/GenApi/IEnumEntry.h \
		/opt/pylon/include/GenApi/IValue.h \
		/opt/pylon/include/GenApi/Types.h \
		/opt/pylon/include/GenApi/Autovector.h \
		/opt/pylon/include/GenApi/IBase.h \
		/opt/pylon/include/GenApi/Reference.h \
		/opt/pylon/include/GenApi/INode.h \
		/opt/pylon/include/GenApi/Container.h \
		/opt/pylon/include/GenApi/IFloat.h \
		/opt/pylon/include/GenApi/IInteger.h \
		/opt/pylon/include/GenApi/ICategory.h \
		/opt/pylon/include/GenApi/IRegister.h \
		/opt/pylon/include/GenApi/IBoolean.h \
		/opt/pylon/include/GenApi/IPort.h \
		/opt/pylon/include/GenApi/IPortRecorder.h \
		/opt/pylon/include/GenApi/IPortConstruct.h \
		/opt/pylon/include/GenApi/IChunkPort.h \
		/opt/pylon/include/GenApi/IString.h \
		/opt/pylon/include/GenApi/INodeMap.h \
		/opt/pylon/include/GenApi/Synch.h \
		/opt/pylon/include/GenApi/IDestroy.h \
		/opt/pylon/include/GenApi/IDeviceInfo.h \
		/opt/pylon/include/GenApi/ISelector.h \
		/opt/pylon/include/GenApi/ICommand.h \
		/opt/pylon/include/GenApi/IUserData.h \
		/opt/pylon/include/GenApi/NodeMapRef.h \
		/opt/pylon/include/GenApi/NodeMapFactory.h \
		/opt/pylon/include/GenApi/GenApiVersion.h \
		/opt/pylon/include/GenApi/NodeCallback.h \
		/opt/pylon/include/GenApi/Persistence.h \
		/opt/pylon/include/GenApi/StructPort.h \
		/opt/pylon/include/GenApi/PortImpl.h \
		/opt/pylon/include/GenApi/SelectorSet.h \
		/opt/pylon/include/GenApi/ISelectorDigit.h \
		/opt/pylon/include/GenApi/GenApiLinkage.h \
		/opt/pylon/include/pylon/stdinclude.h \
		/opt/pylon/include/pylon/TypeMappings.h \
		/opt/pylon/include/pylon/PylonBase.h \
		/opt/pylon/include/pylon/PylonVersionInfo.h \
		/opt/pylon/include/pylon/Info.h \
		/opt/pylon/include/pylon/TlInfo.h \
		/opt/pylon/include/pylon/DeviceClass.h \
		/opt/pylon/include/pylon/DeviceInfo.h \
		/opt/pylon/include/pylon/Container.h \
		/opt/pylon/include/pylon/InterfaceInfo.h \
		/opt/pylon/include/pylon/StaticDefectPixel.h \
		/opt/pylon/include/pylon/DeviceFactory.h \
		/opt/pylon/include/pylon/DeviceAccessMode.h \
		/opt/pylon/include/pylon/PylonVersionNumber.h \
		/opt/pylon/include/pylon/TransportLayer.h \
		/opt/pylon/include/pylon/Interface.h \
		/opt/pylon/include/pylon/TlFactory.h \
		/opt/pylon/include/pylon/EventAdapter.h \
		/opt/pylon/include/pylon/Callback.h \
		/opt/pylon/include/pylon/Device.h \
		/opt/pylon/include/pylon/WaitObject.h \
		/opt/pylon/include/pylon/WaitObjects.h \
		/opt/pylon/include/pylon/StreamGrabber.h \
		/opt/pylon/include/pylon/PixelType.h \
		/opt/pylon/include/pylon/Pixel.h \
		/opt/pylon/include/pylon/PixelTypeMapper.h \
		/opt/pylon/include/GenApi/IEnumerationT.h \
		/opt/pylon/include/GenApi/Compatibility.h \
		/opt/pylon/include/pylon/Result.h \
		/opt/pylon/include/pylon/PayloadType.h \
		/opt/pylon/include/pylon/ResultImage.h \
		/opt/pylon/include/pylon/Image.h \
		/opt/pylon/include/pylon/SharedByteBuffer.h \
		/opt/pylon/include/pylon/PylonDataComponent.h \
		/opt/pylon/include/pylon/PylonDataContainer.h \
		/opt/pylon/include/pylon/ChunkParser.h \
		/opt/pylon/include/pylon/EventGrabber.h \
		/opt/pylon/include/pylon/EventGrabberProxy.h \
		/opt/pylon/include/pylon/NodeMapProxy.h \
		/opt/pylon/include/pylon/AcquireSingleFrameConfiguration.h \
		/opt/pylon/include/pylon/InstantCamera.h \
		/opt/pylon/include/pylon/ImageEventHandler.h \
		/opt/pylon/include/pylon/GrabResultPtr.h \
		/opt/pylon/include/pylon/GrabResultData.h \
		/opt/pylon/include/pylon/ConfigurationEventHandler.h \
		/opt/pylon/include/pylon/CameraEventHandler.h \
		/opt/pylon/include/pylon/BufferFactory.h \
		/opt/pylon/include/pylon/SfncVersion.h \
		/opt/pylon/include/pylon/ECleanup.h \
		/opt/pylon/include/pylon/ERegistrationMode.h \
		/opt/pylon/include/pylon/ETimeoutHandling.h \
		/opt/pylon/include/pylon/_InstantCameraParams.h \
		/opt/pylon/include/pylon/ParameterIncludes.h \
		/opt/pylon/include/pylon/ArrayParameter.h \
		/opt/pylon/include/pylon/Parameter.h \
		/opt/pylon/include/pylon/BooleanParameter.h \
		/opt/pylon/include/pylon/CommandParameter.h \
		/opt/pylon/include/pylon/EnumParameter.h \
		/opt/pylon/include/pylon/FloatParameter.h \
		/opt/pylon/include/pylon/IntegerParameter.h \
		/opt/pylon/include/pylon/StringParameter.h \
		/opt/pylon/include/pylon/EnumParameterT.h \
		/opt/pylon/include/pylon/ConfigurationHelper.h \
		/opt/pylon/include/pylon/InstantCameraArray.h \
		/opt/pylon/include/pylon/AcquireContinuousConfiguration.h \
		/opt/pylon/include/pylon/SoftwareTriggerConfiguration.h \
		/opt/pylon/include/pylon/InstantInterface.h \
		/opt/pylon/include/pylon/_BaslerUniversalInterfaceParams.h \
		/opt/pylon/include/pylon/PylonUtilityIncludes.h \
		/opt/pylon/include/pylon/PylonUtility.h \
		/opt/pylon/include/pylon/PylonImage.h \
		/opt/pylon/include/pylon/PylonImageBase.h \
		/opt/pylon/include/pylon/ReusableImage.h \
		/opt/pylon/include/pylon/ImagePersistence.h \
		/opt/pylon/include/pylon/PixelData.h \
		/opt/pylon/include/pylon/PylonImageUserBufferEventHandler.h \
		/opt/pylon/include/pylon/ImageDecompressor.h \
		/opt/pylon/include/pylon/ImageFormatConverter.h \
		/opt/pylon/include/pylon/_ImageFormatConverterParams.h \
		/opt/pylon/include/pylon/FeaturePersistence.h \
		/opt/pylon/include/pylon/VideoWriter.h \
		/opt/pylon/include/pylon/_VideoWriterParams.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/app_camera_basler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/app_camera_basler -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include basler_camera.h -o moc_basler_camera.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		basler_camera.h \
		/opt/pylon/include/pylon/PylonIncludes.h \
		/opt/pylon/include/pylon/Platform.h \
		/opt/pylon/include/pylon/api_autoconf.h \
		/opt/pylon/include/pylon/PylonLinkage.h \
		/opt/pylon/include/GenICamVersion.h \
		/opt/pylon/include/_GenICamVersion.h \
		/opt/pylon/include/Base/GCLinkage.h \
		/opt/pylon/include/Base/GCTypes.h \
		/opt/pylon/include/Base/GCNamespace.h \
		/opt/pylon/include/Base/GCString.h \
		/opt/pylon/include/Base/GCStringVector.h \
		/opt/pylon/include/GenApi/GenApi.h \
		/opt/pylon/include/Base/GCBase.h \
		/opt/pylon/include/Base/GCArray.h \
		/opt/pylon/include/Base/GCException.h \
		/opt/pylon/include/Base/GCUtilities.h \
		/opt/pylon/include/Base/GCRTSSUtilities.h \
		/opt/pylon/include/GenApi/GenApiDll.h \
		/opt/pylon/include/GenApi/GenApiNamespace.h \
		/opt/pylon/include/GenApi/Pointer.h \
		/opt/pylon/include/GenICamFwd.h \
		/opt/pylon/include/GenApi/IEnumeration.h \
		/opt/pylon/include/GenApi/IEnumEntry.h \
		/opt/pylon/include/GenApi/IValue.h \
		/opt/pylon/include/GenApi/Types.h \
		/opt/pylon/include/GenApi/Autovector.h \
		/opt/pylon/include/GenApi/IBase.h \
		/opt/pylon/include/GenApi/Reference.h \
		/opt/pylon/include/GenApi/INode.h \
		/opt/pylon/include/GenApi/Container.h \
		/opt/pylon/include/GenApi/IFloat.h \
		/opt/pylon/include/GenApi/IInteger.h \
		/opt/pylon/include/GenApi/ICategory.h \
		/opt/pylon/include/GenApi/IRegister.h \
		/opt/pylon/include/GenApi/IBoolean.h \
		/opt/pylon/include/GenApi/IPort.h \
		/opt/pylon/include/GenApi/IPortRecorder.h \
		/opt/pylon/include/GenApi/IPortConstruct.h \
		/opt/pylon/include/GenApi/IChunkPort.h \
		/opt/pylon/include/GenApi/IString.h \
		/opt/pylon/include/GenApi/INodeMap.h \
		/opt/pylon/include/GenApi/Synch.h \
		/opt/pylon/include/GenApi/IDestroy.h \
		/opt/pylon/include/GenApi/IDeviceInfo.h \
		/opt/pylon/include/GenApi/ISelector.h \
		/opt/pylon/include/GenApi/ICommand.h \
		/opt/pylon/include/GenApi/IUserData.h \
		/opt/pylon/include/GenApi/NodeMapRef.h \
		/opt/pylon/include/GenApi/NodeMapFactory.h \
		/opt/pylon/include/GenApi/GenApiVersion.h \
		/opt/pylon/include/GenApi/NodeCallback.h \
		/opt/pylon/include/GenApi/Persistence.h \
		/opt/pylon/include/GenApi/StructPort.h \
		/opt/pylon/include/GenApi/PortImpl.h \
		/opt/pylon/include/GenApi/SelectorSet.h \
		/opt/pylon/include/GenApi/ISelectorDigit.h \
		/opt/pylon/include/GenApi/GenApiLinkage.h \
		/opt/pylon/include/pylon/stdinclude.h \
		/opt/pylon/include/pylon/TypeMappings.h \
		/opt/pylon/include/pylon/PylonBase.h \
		/opt/pylon/include/pylon/PylonVersionInfo.h \
		/opt/pylon/include/pylon/Info.h \
		/opt/pylon/include/pylon/TlInfo.h \
		/opt/pylon/include/pylon/DeviceClass.h \
		/opt/pylon/include/pylon/DeviceInfo.h \
		/opt/pylon/include/pylon/Container.h \
		/opt/pylon/include/pylon/InterfaceInfo.h \
		/opt/pylon/include/pylon/StaticDefectPixel.h \
		/opt/pylon/include/pylon/DeviceFactory.h \
		/opt/pylon/include/pylon/DeviceAccessMode.h \
		/opt/pylon/include/pylon/PylonVersionNumber.h \
		/opt/pylon/include/pylon/TransportLayer.h \
		/opt/pylon/include/pylon/Interface.h \
		/opt/pylon/include/pylon/TlFactory.h \
		/opt/pylon/include/pylon/EventAdapter.h \
		/opt/pylon/include/pylon/Callback.h \
		/opt/pylon/include/pylon/Device.h \
		/opt/pylon/include/pylon/WaitObject.h \
		/opt/pylon/include/pylon/WaitObjects.h \
		/opt/pylon/include/pylon/StreamGrabber.h \
		/opt/pylon/include/pylon/PixelType.h \
		/opt/pylon/include/pylon/Pixel.h \
		/opt/pylon/include/pylon/PixelTypeMapper.h \
		/opt/pylon/include/GenApi/IEnumerationT.h \
		/opt/pylon/include/GenApi/Compatibility.h \
		/opt/pylon/include/pylon/Result.h \
		/opt/pylon/include/pylon/PayloadType.h \
		/opt/pylon/include/pylon/ResultImage.h \
		/opt/pylon/include/pylon/Image.h \
		/opt/pylon/include/pylon/SharedByteBuffer.h \
		/opt/pylon/include/pylon/PylonDataComponent.h \
		/opt/pylon/include/pylon/PylonDataContainer.h \
		/opt/pylon/include/pylon/ChunkParser.h \
		/opt/pylon/include/pylon/EventGrabber.h \
		/opt/pylon/include/pylon/EventGrabberProxy.h \
		/opt/pylon/include/pylon/NodeMapProxy.h \
		/opt/pylon/include/pylon/AcquireSingleFrameConfiguration.h \
		/opt/pylon/include/pylon/InstantCamera.h \
		/opt/pylon/include/pylon/ImageEventHandler.h \
		/opt/pylon/include/pylon/GrabResultPtr.h \
		/opt/pylon/include/pylon/GrabResultData.h \
		/opt/pylon/include/pylon/ConfigurationEventHandler.h \
		/opt/pylon/include/pylon/CameraEventHandler.h \
		/opt/pylon/include/pylon/BufferFactory.h \
		/opt/pylon/include/pylon/SfncVersion.h \
		/opt/pylon/include/pylon/ECleanup.h \
		/opt/pylon/include/pylon/ERegistrationMode.h \
		/opt/pylon/include/pylon/ETimeoutHandling.h \
		/opt/pylon/include/pylon/_InstantCameraParams.h \
		/opt/pylon/include/pylon/ParameterIncludes.h \
		/opt/pylon/include/pylon/ArrayParameter.h \
		/opt/pylon/include/pylon/Parameter.h \
		/opt/pylon/include/pylon/BooleanParameter.h \
		/opt/pylon/include/pylon/CommandParameter.h \
		/opt/pylon/include/pylon/EnumParameter.h \
		/opt/pylon/include/pylon/FloatParameter.h \
		/opt/pylon/include/pylon/IntegerParameter.h \
		/opt/pylon/include/pylon/StringParameter.h \
		/opt/pylon/include/pylon/EnumParameterT.h \
		/opt/pylon/include/pylon/ConfigurationHelper.h \
		/opt/pylon/include/pylon/InstantCameraArray.h \
		/opt/pylon/include/pylon/AcquireContinuousConfiguration.h \
		/opt/pylon/include/pylon/SoftwareTriggerConfiguration.h \
		/opt/pylon/include/pylon/InstantInterface.h \
		/opt/pylon/include/pylon/_BaslerUniversalInterfaceParams.h \
		/opt/pylon/include/pylon/PylonUtilityIncludes.h \
		/opt/pylon/include/pylon/PylonUtility.h \
		/opt/pylon/include/pylon/PylonImage.h \
		/opt/pylon/include/pylon/PylonImageBase.h \
		/opt/pylon/include/pylon/ReusableImage.h \
		/opt/pylon/include/pylon/ImagePersistence.h \
		/opt/pylon/include/pylon/PixelData.h \
		/opt/pylon/include/pylon/PylonImageUserBufferEventHandler.h \
		/opt/pylon/include/pylon/ImageDecompressor.h \
		/opt/pylon/include/pylon/ImageFormatConverter.h \
		/opt/pylon/include/pylon/_ImageFormatConverterParams.h \
		/opt/pylon/include/pylon/FeaturePersistence.h \
		/opt/pylon/include/pylon/VideoWriter.h \
		/opt/pylon/include/pylon/_VideoWriterParams.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		basler_camera.h \
		/opt/pylon/include/pylon/PylonIncludes.h \
		/opt/pylon/include/pylon/Platform.h \
		/opt/pylon/include/pylon/api_autoconf.h \
		/opt/pylon/include/pylon/PylonLinkage.h \
		/opt/pylon/include/GenICamVersion.h \
		/opt/pylon/include/_GenICamVersion.h \
		/opt/pylon/include/Base/GCLinkage.h \
		/opt/pylon/include/Base/GCTypes.h \
		/opt/pylon/include/Base/GCNamespace.h \
		/opt/pylon/include/Base/GCString.h \
		/opt/pylon/include/Base/GCStringVector.h \
		/opt/pylon/include/GenApi/GenApi.h \
		/opt/pylon/include/Base/GCBase.h \
		/opt/pylon/include/Base/GCArray.h \
		/opt/pylon/include/Base/GCException.h \
		/opt/pylon/include/Base/GCUtilities.h \
		/opt/pylon/include/Base/GCRTSSUtilities.h \
		/opt/pylon/include/GenApi/GenApiDll.h \
		/opt/pylon/include/GenApi/GenApiNamespace.h \
		/opt/pylon/include/GenApi/Pointer.h \
		/opt/pylon/include/GenICamFwd.h \
		/opt/pylon/include/GenApi/IEnumeration.h \
		/opt/pylon/include/GenApi/IEnumEntry.h \
		/opt/pylon/include/GenApi/IValue.h \
		/opt/pylon/include/GenApi/Types.h \
		/opt/pylon/include/GenApi/Autovector.h \
		/opt/pylon/include/GenApi/IBase.h \
		/opt/pylon/include/GenApi/Reference.h \
		/opt/pylon/include/GenApi/INode.h \
		/opt/pylon/include/GenApi/Container.h \
		/opt/pylon/include/GenApi/IFloat.h \
		/opt/pylon/include/GenApi/IInteger.h \
		/opt/pylon/include/GenApi/ICategory.h \
		/opt/pylon/include/GenApi/IRegister.h \
		/opt/pylon/include/GenApi/IBoolean.h \
		/opt/pylon/include/GenApi/IPort.h \
		/opt/pylon/include/GenApi/IPortRecorder.h \
		/opt/pylon/include/GenApi/IPortConstruct.h \
		/opt/pylon/include/GenApi/IChunkPort.h \
		/opt/pylon/include/GenApi/IString.h \
		/opt/pylon/include/GenApi/INodeMap.h \
		/opt/pylon/include/GenApi/Synch.h \
		/opt/pylon/include/GenApi/IDestroy.h \
		/opt/pylon/include/GenApi/IDeviceInfo.h \
		/opt/pylon/include/GenApi/ISelector.h \
		/opt/pylon/include/GenApi/ICommand.h \
		/opt/pylon/include/GenApi/IUserData.h \
		/opt/pylon/include/GenApi/NodeMapRef.h \
		/opt/pylon/include/GenApi/NodeMapFactory.h \
		/opt/pylon/include/GenApi/GenApiVersion.h \
		/opt/pylon/include/GenApi/NodeCallback.h \
		/opt/pylon/include/GenApi/Persistence.h \
		/opt/pylon/include/GenApi/StructPort.h \
		/opt/pylon/include/GenApi/PortImpl.h \
		/opt/pylon/include/GenApi/SelectorSet.h \
		/opt/pylon/include/GenApi/ISelectorDigit.h \
		/opt/pylon/include/GenApi/GenApiLinkage.h \
		/opt/pylon/include/pylon/stdinclude.h \
		/opt/pylon/include/pylon/TypeMappings.h \
		/opt/pylon/include/pylon/PylonBase.h \
		/opt/pylon/include/pylon/PylonVersionInfo.h \
		/opt/pylon/include/pylon/Info.h \
		/opt/pylon/include/pylon/TlInfo.h \
		/opt/pylon/include/pylon/DeviceClass.h \
		/opt/pylon/include/pylon/DeviceInfo.h \
		/opt/pylon/include/pylon/Container.h \
		/opt/pylon/include/pylon/InterfaceInfo.h \
		/opt/pylon/include/pylon/StaticDefectPixel.h \
		/opt/pylon/include/pylon/DeviceFactory.h \
		/opt/pylon/include/pylon/DeviceAccessMode.h \
		/opt/pylon/include/pylon/PylonVersionNumber.h \
		/opt/pylon/include/pylon/TransportLayer.h \
		/opt/pylon/include/pylon/Interface.h \
		/opt/pylon/include/pylon/TlFactory.h \
		/opt/pylon/include/pylon/EventAdapter.h \
		/opt/pylon/include/pylon/Callback.h \
		/opt/pylon/include/pylon/Device.h \
		/opt/pylon/include/pylon/WaitObject.h \
		/opt/pylon/include/pylon/WaitObjects.h \
		/opt/pylon/include/pylon/StreamGrabber.h \
		/opt/pylon/include/pylon/PixelType.h \
		/opt/pylon/include/pylon/Pixel.h \
		/opt/pylon/include/pylon/PixelTypeMapper.h \
		/opt/pylon/include/GenApi/IEnumerationT.h \
		/opt/pylon/include/GenApi/Compatibility.h \
		/opt/pylon/include/pylon/Result.h \
		/opt/pylon/include/pylon/PayloadType.h \
		/opt/pylon/include/pylon/ResultImage.h \
		/opt/pylon/include/pylon/Image.h \
		/opt/pylon/include/pylon/SharedByteBuffer.h \
		/opt/pylon/include/pylon/PylonDataComponent.h \
		/opt/pylon/include/pylon/PylonDataContainer.h \
		/opt/pylon/include/pylon/ChunkParser.h \
		/opt/pylon/include/pylon/EventGrabber.h \
		/opt/pylon/include/pylon/EventGrabberProxy.h \
		/opt/pylon/include/pylon/NodeMapProxy.h \
		/opt/pylon/include/pylon/AcquireSingleFrameConfiguration.h \
		/opt/pylon/include/pylon/InstantCamera.h \
		/opt/pylon/include/pylon/ImageEventHandler.h \
		/opt/pylon/include/pylon/GrabResultPtr.h \
		/opt/pylon/include/pylon/GrabResultData.h \
		/opt/pylon/include/pylon/ConfigurationEventHandler.h \
		/opt/pylon/include/pylon/CameraEventHandler.h \
		/opt/pylon/include/pylon/BufferFactory.h \
		/opt/pylon/include/pylon/SfncVersion.h \
		/opt/pylon/include/pylon/ECleanup.h \
		/opt/pylon/include/pylon/ERegistrationMode.h \
		/opt/pylon/include/pylon/ETimeoutHandling.h \
		/opt/pylon/include/pylon/_InstantCameraParams.h \
		/opt/pylon/include/pylon/ParameterIncludes.h \
		/opt/pylon/include/pylon/ArrayParameter.h \
		/opt/pylon/include/pylon/Parameter.h \
		/opt/pylon/include/pylon/BooleanParameter.h \
		/opt/pylon/include/pylon/CommandParameter.h \
		/opt/pylon/include/pylon/EnumParameter.h \
		/opt/pylon/include/pylon/FloatParameter.h \
		/opt/pylon/include/pylon/IntegerParameter.h \
		/opt/pylon/include/pylon/StringParameter.h \
		/opt/pylon/include/pylon/EnumParameterT.h \
		/opt/pylon/include/pylon/ConfigurationHelper.h \
		/opt/pylon/include/pylon/InstantCameraArray.h \
		/opt/pylon/include/pylon/AcquireContinuousConfiguration.h \
		/opt/pylon/include/pylon/SoftwareTriggerConfiguration.h \
		/opt/pylon/include/pylon/InstantInterface.h \
		/opt/pylon/include/pylon/_BaslerUniversalInterfaceParams.h \
		/opt/pylon/include/pylon/PylonUtilityIncludes.h \
		/opt/pylon/include/pylon/PylonUtility.h \
		/opt/pylon/include/pylon/PylonImage.h \
		/opt/pylon/include/pylon/PylonImageBase.h \
		/opt/pylon/include/pylon/ReusableImage.h \
		/opt/pylon/include/pylon/ImagePersistence.h \
		/opt/pylon/include/pylon/PixelData.h \
		/opt/pylon/include/pylon/PylonImageUserBufferEventHandler.h \
		/opt/pylon/include/pylon/ImageDecompressor.h \
		/opt/pylon/include/pylon/ImageFormatConverter.h \
		/opt/pylon/include/pylon/_ImageFormatConverterParams.h \
		/opt/pylon/include/pylon/FeaturePersistence.h \
		/opt/pylon/include/pylon/VideoWriter.h \
		/opt/pylon/include/pylon/_VideoWriterParams.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

basler_camera.o: basler_camera.cpp basler_camera.h \
		/opt/pylon/include/pylon/PylonIncludes.h \
		/opt/pylon/include/pylon/Platform.h \
		/opt/pylon/include/pylon/api_autoconf.h \
		/opt/pylon/include/pylon/PylonLinkage.h \
		/opt/pylon/include/GenICamVersion.h \
		/opt/pylon/include/_GenICamVersion.h \
		/opt/pylon/include/Base/GCLinkage.h \
		/opt/pylon/include/Base/GCTypes.h \
		/opt/pylon/include/Base/GCNamespace.h \
		/opt/pylon/include/Base/GCString.h \
		/opt/pylon/include/Base/GCStringVector.h \
		/opt/pylon/include/GenApi/GenApi.h \
		/opt/pylon/include/Base/GCBase.h \
		/opt/pylon/include/Base/GCArray.h \
		/opt/pylon/include/Base/GCException.h \
		/opt/pylon/include/Base/GCUtilities.h \
		/opt/pylon/include/Base/GCRTSSUtilities.h \
		/opt/pylon/include/GenApi/GenApiDll.h \
		/opt/pylon/include/GenApi/GenApiNamespace.h \
		/opt/pylon/include/GenApi/Pointer.h \
		/opt/pylon/include/GenICamFwd.h \
		/opt/pylon/include/GenApi/IEnumeration.h \
		/opt/pylon/include/GenApi/IEnumEntry.h \
		/opt/pylon/include/GenApi/IValue.h \
		/opt/pylon/include/GenApi/Types.h \
		/opt/pylon/include/GenApi/Autovector.h \
		/opt/pylon/include/GenApi/IBase.h \
		/opt/pylon/include/GenApi/Reference.h \
		/opt/pylon/include/GenApi/INode.h \
		/opt/pylon/include/GenApi/Container.h \
		/opt/pylon/include/GenApi/IFloat.h \
		/opt/pylon/include/GenApi/IInteger.h \
		/opt/pylon/include/GenApi/ICategory.h \
		/opt/pylon/include/GenApi/IRegister.h \
		/opt/pylon/include/GenApi/IBoolean.h \
		/opt/pylon/include/GenApi/IPort.h \
		/opt/pylon/include/GenApi/IPortRecorder.h \
		/opt/pylon/include/GenApi/IPortConstruct.h \
		/opt/pylon/include/GenApi/IChunkPort.h \
		/opt/pylon/include/GenApi/IString.h \
		/opt/pylon/include/GenApi/INodeMap.h \
		/opt/pylon/include/GenApi/Synch.h \
		/opt/pylon/include/GenApi/IDestroy.h \
		/opt/pylon/include/GenApi/IDeviceInfo.h \
		/opt/pylon/include/GenApi/ISelector.h \
		/opt/pylon/include/GenApi/ICommand.h \
		/opt/pylon/include/GenApi/IUserData.h \
		/opt/pylon/include/GenApi/NodeMapRef.h \
		/opt/pylon/include/GenApi/NodeMapFactory.h \
		/opt/pylon/include/GenApi/GenApiVersion.h \
		/opt/pylon/include/GenApi/NodeCallback.h \
		/opt/pylon/include/GenApi/Persistence.h \
		/opt/pylon/include/GenApi/StructPort.h \
		/opt/pylon/include/GenApi/PortImpl.h \
		/opt/pylon/include/GenApi/SelectorSet.h \
		/opt/pylon/include/GenApi/ISelectorDigit.h \
		/opt/pylon/include/GenApi/GenApiLinkage.h \
		/opt/pylon/include/pylon/stdinclude.h \
		/opt/pylon/include/pylon/TypeMappings.h \
		/opt/pylon/include/pylon/PylonBase.h \
		/opt/pylon/include/pylon/PylonVersionInfo.h \
		/opt/pylon/include/pylon/Info.h \
		/opt/pylon/include/pylon/TlInfo.h \
		/opt/pylon/include/pylon/DeviceClass.h \
		/opt/pylon/include/pylon/DeviceInfo.h \
		/opt/pylon/include/pylon/Container.h \
		/opt/pylon/include/pylon/InterfaceInfo.h \
		/opt/pylon/include/pylon/StaticDefectPixel.h \
		/opt/pylon/include/pylon/DeviceFactory.h \
		/opt/pylon/include/pylon/DeviceAccessMode.h \
		/opt/pylon/include/pylon/PylonVersionNumber.h \
		/opt/pylon/include/pylon/TransportLayer.h \
		/opt/pylon/include/pylon/Interface.h \
		/opt/pylon/include/pylon/TlFactory.h \
		/opt/pylon/include/pylon/EventAdapter.h \
		/opt/pylon/include/pylon/Callback.h \
		/opt/pylon/include/pylon/Device.h \
		/opt/pylon/include/pylon/WaitObject.h \
		/opt/pylon/include/pylon/WaitObjects.h \
		/opt/pylon/include/pylon/StreamGrabber.h \
		/opt/pylon/include/pylon/PixelType.h \
		/opt/pylon/include/pylon/Pixel.h \
		/opt/pylon/include/pylon/PixelTypeMapper.h \
		/opt/pylon/include/GenApi/IEnumerationT.h \
		/opt/pylon/include/GenApi/Compatibility.h \
		/opt/pylon/include/pylon/Result.h \
		/opt/pylon/include/pylon/PayloadType.h \
		/opt/pylon/include/pylon/ResultImage.h \
		/opt/pylon/include/pylon/Image.h \
		/opt/pylon/include/pylon/SharedByteBuffer.h \
		/opt/pylon/include/pylon/PylonDataComponent.h \
		/opt/pylon/include/pylon/PylonDataContainer.h \
		/opt/pylon/include/pylon/ChunkParser.h \
		/opt/pylon/include/pylon/EventGrabber.h \
		/opt/pylon/include/pylon/EventGrabberProxy.h \
		/opt/pylon/include/pylon/NodeMapProxy.h \
		/opt/pylon/include/pylon/AcquireSingleFrameConfiguration.h \
		/opt/pylon/include/pylon/InstantCamera.h \
		/opt/pylon/include/pylon/ImageEventHandler.h \
		/opt/pylon/include/pylon/GrabResultPtr.h \
		/opt/pylon/include/pylon/GrabResultData.h \
		/opt/pylon/include/pylon/ConfigurationEventHandler.h \
		/opt/pylon/include/pylon/CameraEventHandler.h \
		/opt/pylon/include/pylon/BufferFactory.h \
		/opt/pylon/include/pylon/SfncVersion.h \
		/opt/pylon/include/pylon/ECleanup.h \
		/opt/pylon/include/pylon/ERegistrationMode.h \
		/opt/pylon/include/pylon/ETimeoutHandling.h \
		/opt/pylon/include/pylon/_InstantCameraParams.h \
		/opt/pylon/include/pylon/ParameterIncludes.h \
		/opt/pylon/include/pylon/ArrayParameter.h \
		/opt/pylon/include/pylon/Parameter.h \
		/opt/pylon/include/pylon/BooleanParameter.h \
		/opt/pylon/include/pylon/CommandParameter.h \
		/opt/pylon/include/pylon/EnumParameter.h \
		/opt/pylon/include/pylon/FloatParameter.h \
		/opt/pylon/include/pylon/IntegerParameter.h \
		/opt/pylon/include/pylon/StringParameter.h \
		/opt/pylon/include/pylon/EnumParameterT.h \
		/opt/pylon/include/pylon/ConfigurationHelper.h \
		/opt/pylon/include/pylon/InstantCameraArray.h \
		/opt/pylon/include/pylon/AcquireContinuousConfiguration.h \
		/opt/pylon/include/pylon/SoftwareTriggerConfiguration.h \
		/opt/pylon/include/pylon/InstantInterface.h \
		/opt/pylon/include/pylon/_BaslerUniversalInterfaceParams.h \
		/opt/pylon/include/pylon/PylonUtilityIncludes.h \
		/opt/pylon/include/pylon/PylonUtility.h \
		/opt/pylon/include/pylon/PylonImage.h \
		/opt/pylon/include/pylon/PylonImageBase.h \
		/opt/pylon/include/pylon/ReusableImage.h \
		/opt/pylon/include/pylon/ImagePersistence.h \
		/opt/pylon/include/pylon/PixelData.h \
		/opt/pylon/include/pylon/PylonImageUserBufferEventHandler.h \
		/opt/pylon/include/pylon/ImageDecompressor.h \
		/opt/pylon/include/pylon/ImageFormatConverter.h \
		/opt/pylon/include/pylon/_ImageFormatConverterParams.h \
		/opt/pylon/include/pylon/FeaturePersistence.h \
		/opt/pylon/include/pylon/VideoWriter.h \
		/opt/pylon/include/pylon/_VideoWriterParams.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basler_camera.o basler_camera.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_basler_camera.o: moc_basler_camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_basler_camera.o moc_basler_camera.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/app_camera_basler/bin || mkdir -p $(INSTALL_ROOT)/opt/app_camera_basler/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/app_camera_basler/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/app_camera_basler/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/app_camera_basler/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/app_camera_basler/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

